name: 'ng_dart_ombdbapi'
version: 0.0.1

author: <Boris-Wilfried>

environment:
  sdk: '>=1.13.1 <2.0.0'

dependencies:
  analyzer: any
  browser: any
  angular2: 2.0.0-beta.17
  script_inliner: any
  dart_to_js_script_rewriter: any
  quiver: any
  chartjs: any
transformers:
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes:
     - package:angular2/common.dart#COMMON_PIPES
    entry_points: web/main.dart
- script_inliner
- dart_to_js_script_rewriter
- $dart2js:
    csp: true # Content Security Policy
    checked: false
    $exclude: bin
    minify: true
    commandLineOptions: ['--enable-experimental-mirrors','--trust-type-annotations', '--trust-primitives']