name: 'ng_dart_ombdbapi'
version: 0.0.1

author: <Boris-Wilfried>

environment:
  sdk: '1.16.0'

dependencies:
  angular: '1.1.2+2'
  chartjs: any
  dart_to_js_script_rewriter: "^1.0.1"
  quiver: "^0.22.0"
  web_components: "0.12.0+4"

dev_dependencies:
  unittest: '0.11.6+4'
  test_runner: "^0.2.16+1"

transformers:
- angular
- dart_to_js_script_rewriter
- $dart2js:
    csp: true # Content Security Policy
    checked: false
    $exclude: bin
    minify: true
    commandLineOptions: ['--enable-experimental-mirrors','--trust-type-annotations', '--trust-primitives']